### ISSUE TITLE
CI for dev,master testcases

### ISSUE THREAD

**Issue by GiovanniCardamone** [BeatingCodingame/python3-code-vs-zombie#13]
Please add CI integration for run testcase when PR is made to dev, master branches.

We really need that!

**Comment by Symone95** [comment]
Hi @GiovanniCardamone,
I just added CI integration to run testcases when we make a PR to dev and master branches.

Simone

**Comment by GiovanniCardamone** [comment]
I Will check it tomorrow

**Comment by GiovanniCardamone** [comment]
Please always remember to link branch with the feature
